@startuml
actor Actor as Actor
control BrandController as BrandController

Actor -> BrandController : getDepartment
activate BrandController
BrandController -> BrandService : getOne
activate BrandService
BrandService --> BrandController
deactivate BrandService
BrandController -> BrandAmenitieService : getAllByBrandIDActivate
activate BrandAmenitieService
BrandAmenitieService --> BrandController
deactivate BrandAmenitieService
BrandController -> DepartmentService : getDepartmentByBrandID
activate DepartmentService
DepartmentService --> BrandController
deactivate DepartmentService
BrandController -> DepartmentService : getDepartmentFeedbackOfBrandOwner
activate DepartmentService
DepartmentService --> BrandController
deactivate DepartmentService
BrandController -> BrandService : getFeedbackOfBrandDetailStat
activate BrandService
BrandService --> BrandController
deactivate BrandService
loop departmentDTOList
BrandController -> DepartmentFeatureService : getDepartmentFeatures
activate DepartmentFeatureService
DepartmentFeatureService --> BrandController
deactivate DepartmentFeatureService
end
return
@enduml