@startuml
participant Actor
Actor -> ConfirmRequestController : performCheckIn
activate ConfirmRequestController
ConfirmRequestController -> OrderDetailService : getUserNameByOrderDetailId
activate OrderDetailService
OrderDetailService -> OrderDetailServiceImpl : getUserNameByOrderDetailId
activate OrderDetailServiceImpl
OrderDetailServiceImpl -> OrderDetailRepository : getUserNameByOrderDetailId
activate OrderDetailRepository
OrderDetailRepository --> OrderDetailServiceImpl
deactivate OrderDetailRepository
OrderDetailServiceImpl --> OrderDetailService
deactivate OrderDetailServiceImpl
OrderDetailService --> ConfirmRequestController
deactivate OrderDetailService
alt cancel.equals("no")
ConfirmRequestController -> NotificationService : insertNotification
activate NotificationService
NotificationService -> NotificationServiceImpl : insertNotification
activate NotificationServiceImpl
NotificationServiceImpl -> NotificationRepository : insertNotification
activate NotificationRepository
NotificationRepository --> NotificationServiceImpl
deactivate NotificationRepository
NotificationServiceImpl --> NotificationService
deactivate NotificationServiceImpl
NotificationService --> ConfirmRequestController
deactivate NotificationService
ConfirmRequestController -> WebSocketService : notifyEmployee
activate WebSocketService
WebSocketService -> WebSocketServiceImpl : notifyEmployee
activate WebSocketServiceImpl
WebSocketServiceImpl --> WebSocketService
deactivate WebSocketServiceImpl
WebSocketService --> ConfirmRequestController
deactivate WebSocketService
ConfirmRequestController -> EmployeeService : insertToCheckInHistory
activate EmployeeService
EmployeeService -> EmployeeServiceImpl : insertToCheckInHistory
activate EmployeeServiceImpl
EmployeeServiceImpl -> EmployeeRepository : insertToCheckInHistory
activate EmployeeRepository
EmployeeRepository --> EmployeeServiceImpl
deactivate EmployeeRepository
EmployeeServiceImpl --> EmployeeService
deactivate EmployeeServiceImpl
EmployeeService --> ConfirmRequestController
deactivate EmployeeService
ConfirmRequestController -> OrderDetailService : updateOrderDetailsUseStatus
activate OrderDetailService
OrderDetailService -> OrderDetailServiceImpl : updateOrderDetailsUseStatus
activate OrderDetailServiceImpl
OrderDetailServiceImpl -> OrderDetailRepository : updateOrderDetailsUseStatus
activate OrderDetailRepository
OrderDetailRepository --> OrderDetailServiceImpl
deactivate OrderDetailRepository
OrderDetailServiceImpl --> OrderDetailService
deactivate OrderDetailServiceImpl
OrderDetailService --> ConfirmRequestController
deactivate OrderDetailService
ConfirmRequestController -> OrderDetailService : isFixedGymPlan
activate OrderDetailService
OrderDetailService -> OrderDetailServiceImpl : isFixedGymPlan
activate OrderDetailServiceImpl
OrderDetailServiceImpl -> OrderDetailRepository : isFixedGymPlan
activate OrderDetailRepository
OrderDetailRepository --> OrderDetailServiceImpl
deactivate OrderDetailRepository
OrderDetailServiceImpl --> OrderDetailService
deactivate OrderDetailServiceImpl
OrderDetailService --> ConfirmRequestController
deactivate OrderDetailService
alt orderDetailService.isFixedGymPlan(orderDetailId)
ConfirmRequestController -> OrderDetailService : decreaseDuration
activate OrderDetailService
OrderDetailService -> OrderDetailServiceImpl : decreaseDuration
activate OrderDetailServiceImpl
OrderDetailServiceImpl -> OrderDetailRepository : decreaseDuration
activate OrderDetailRepository
OrderDetailRepository --> OrderDetailServiceImpl
deactivate OrderDetailRepository
OrderDetailServiceImpl --> OrderDetailService
deactivate OrderDetailServiceImpl
OrderDetailService --> ConfirmRequestController
deactivate OrderDetailService
end
else 
ConfirmRequestController -> NotificationService : insertNotification
activate NotificationService
NotificationService -> NotificationServiceImpl : insertNotification
activate NotificationServiceImpl
NotificationServiceImpl -> NotificationRepository : insertNotification
activate NotificationRepository
NotificationRepository --> NotificationServiceImpl
deactivate NotificationRepository
NotificationServiceImpl --> NotificationService
deactivate NotificationServiceImpl
NotificationService --> ConfirmRequestController
deactivate NotificationService
ConfirmRequestController -> WebSocketService : notifyEmployee
activate WebSocketService
WebSocketService -> WebSocketServiceImpl : notifyEmployee
activate WebSocketServiceImpl
WebSocketServiceImpl --> WebSocketService
deactivate WebSocketServiceImpl
WebSocketService --> ConfirmRequestController
deactivate WebSocketService
end
return
@enduml